version: "3.9"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://post:post@db:5432/post
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: post
      POSTGRES_DB: post
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-postgres:
