version: "3.9"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: post
      POSTGRES_USER: post
      POSTGRES_PASSWORD: post

volumes:
  db_postgres:
