ARG NODE_VERSION=20.2.0
ARG PNPM_VERSION=8.6.5

FROM node:${NODE_VERSION}-alpine as base

RUN npm install -g pnpm@${PNPM_VERSION}

WORKDIR /usr/src/app

COPY package*.json ./

RUN pnpm i

COPY . .

RUN pnpm i prisma 

RUN prisma generate

CMD ["pnpm", "dev"]